name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Surefire Report
        if: success() || failure()
        uses: ScaCap/action-surefire-report@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Gist with Test Results
        if: success() || failure()
        run: |
          sudo apt-get install -y jq
          TEST_RESULTS=$(find . -name 'TEST-*.xml' -exec cat {} + | grep -oP '(?<=<testsuite ).*?(?=>)' | jq -R 'split(" ") | map(split("=") | {(.[0]): .[1]}) | add')
          PASSED=$(echo $TEST_RESULTS | jq '[.tests - .failures - .errors - .skipped] | add')
          TOTAL=$(echo $TEST_RESULTS | jq '[.tests] | add')
          JSON=$(jq -n --arg passed "$PASSED" --arg total "$TOTAL" '{"schemaVersion": 1, "label": "tests", "message": "\($passed)/\($total)", "color": "green"}')
          echo $JSON > test-results.json
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d @test-results.json https://api.github.com/gists/name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Surefire Report
        if: success() || failure()
        uses: ScaCap/action-surefire-report@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Gist with Test Results
        if: success() || failure()
        run: |
          sudo apt-get install -y jq
          TEST_RESULTS=$(find . -name 'TEST-*.xml' -exec cat {} + | grep -oP '(?<=<testsuite ).*?(?=>)' | jq -R 'split(" ") | map(split("=") | {(.[0]): .[1]}) | add')
          PASSED=$(echo $TEST_RESULTS | jq '[.tests - .failures - .errors - .skipped] | add')
          TOTAL=$(echo $TEST_RESULTS | jq '[.tests] | add')
          JSON=$(jq -n --arg passed "$PASSED" --arg total "$TOTAL" '{"schemaVersion": 1, "label": "tests", "message": "\($passed)/\($total)", "color": "green"}')
          echo $JSON > test-results.json
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d @test-results.json https://api.github.com/gists/8a0997d8fcd131e6d852e6cea09fa022